#+TITLE: OpenAxiom
#+SUBTITLE: An open source universal TTRPG engine

OpenAxiom is a free and open source tabletop roleplaying game (TTRPG) engine inspired by GURPS. OpenAxiom has a few features:

* A universal engine
:PROPERTIES:
:ID:       76E78AEA-D47E-4E09-8D73-F2EAF0FB1D32
:END:

OpenAxiom is called a TTRPG "engine," instead of just a TTRPG, because it doesn't come with many of the features you'd expect from a fully-fledged TTRPG, such as lists of predefined gear, monsters, locations, lore, races, classes, skills, traits, and so on. Instead, it's /just/ the chore mechanics, designed to be setting and genre agnostic.

Eventually, modular free and open source "packs" will provide the various other components you need to play, which you can mix and match as needed, although a core pack of sensible skills, traits, and NPCs almost any setting needs is recommended.

OpenAxiom is also explicitly designed to be extremely easy to write packs for, and easy to adapt material from other games for. This should mean that things like GURPS sourcebooks will serve nicely with this system! (Seriously, Steve Jackson Games rocks, give them some love.)

* Simulationist
:PROPERTIES:
:ID:       F0D882B2-371F-4B46-81D3-E46777EAE3C0
:END:

OpenAxiom also attempts to be simulationist: there are no mechanics for the same of mechanics, seemingly hastily themed after the fact like in a European boardgame. Instead, everything in the game's system should feel like it directly corresponds to, and simulates, something in the game world, in a satisfying and specific way, with real payoffs and consequences mechanically determined and mechanically enforced, because the best stories are born from that kind of surprising story generation that can't just be smoothed away.

Importantly, howver, to avoid overly baroque complexity while trying to be genreless, OpenAxiom provides an engine for a /logic of action and consequences/, of /means and ends/, and that's it. It doesn't know, or have to know, about magic or laser blasters. All it knows is how to simulate an attempt to act, and the results of that action in the abstract. Players assign names to the actions and the outcomes, and the game processes them as it would any other set of actions and outcomes, producing a result. There's still a direct, one to one correspondence, but it's made in the space between the game and the player, as they assign words to things. It's like a logic programming language: it doesn't know what the words actually mean, but it can still simulate things anyway.

* Chrunchy across the board
:PROPERTIES:
:ID:       C53291DF-5C13-4572-8D92-EF9ACD66B6F7
:END:

A lot of TTRPGs, even universal ones, spend a lot more time developing combat mechanics than they do social and story mechanics. This is understandable, because developing the former is much easier and more well-understood, but also unfortunate, and undermines the supposed universality of the system. OpenAxiom seeks to provide mechanical crunch for everything, across the board, whether it's character development, story beats, social interactions, politics, or combat.

This means that OpenAxiom respects your story, characters, and their social interactions just as much as their combat prowess. This is not just a game for wargamers and murder hobos, it is also a game for those who want to explore the politics of taking state power through long political intrigue, or toppling a rogue nation, or resolving a harem situation.

* Harsh but fair
:PROPERTIES:
:ID:       94392421-E198-441E-9E15-71A4073D2A8E
:END:

Stories only matter when they have stakes. OpenAxiom is designed to ensure you have those stakes. This is a game that will rough you up, that intends to chew you up and spit you out if you aren't careful. However, nothing is overly random: every risk is a choice, every outcome preventable or something you can prepare for, and every bad outcome this side of death is recoverable, even if the road is long and hard. Learn to roll with the punches, embrace the Dwarf Fortress definition of fun, and grin and laugh in the face of death.

* Easy to understand
:PROPERTIES:
:ID:       7D06EB31-DDBB-46F1-A48D-44200FAECFF7
:END:

Despite its depth, a primary goal for OpenAxiom is to be small, easy to read, and easy to understand.

For this reason, OpenAxiom attempts to avoid being overly complex by eschewing complex calculations and multidimensional tables. Everything can and should be able to be resolved, no matter how complex the situation, by under five additions or subtractions, and one linear table lookup. Not even any multiplication needed!

Similarly, OpenAxiom is exclusively written in a special simple prose designed to be easy for anyone to comprehend --- to never trip you up with an unexpected subclause.
