#+TITLE: Dreamforge

* Dreamforge
:PROPERTIES:
:ID:       6FFBCBC5-20EA-44B1-88E6-50BE3FC3CACA
:END:

*An engine for your imagination.*

Welcome to Dreamforge, a tabletop roleplaying game designed for ultimate creative freedom.

Have you ever had a story you wanted to tell, a world you wanted to explore, but couldn't find the right system? Dreamforge is your answer. It is a universal toolkit for crafting adventures in any genre and any setting. From the lowest fantasy to the hardest science fiction, from sprawling space operas to intimate historical dramas, the rules get out of your way and let you tell the story you want to tell.

** Your World, Your Rules
:PROPERTIES:
:ID:       3A4167FA-630D-4807-922E-30B25EA81EA8
:END:

Dreamforge is built on a foundation of simple, intuitive mechanics that are both flexible and robust.

*** Limitless Worlds
Dreamforge is not tied to a single setting. The game is setting-agnostic. This provides a canvas for players to create their own unique universe. While the core system is genre-neutral, Dreamforge will offer setting and genre packs. These packs provide libraries of locations, traits, and skills for storytellers to draw upon.

*** Fluid Characters
Dreamforge characters are not defined by restrictive classes or a predefined list of relatively fixed attributes. Instead, characters possess inherent abilities and disabilities, called traits, which correspond directly to skills, providing passive bonuses or disadvantages. This allows for maximum creativity in character creation, and the possibility of adapting and overcoming a character's traits by increasing their skills.

*** Simple, Not Simplistic
The rules are easy to learn. The game uses only basic arithmetic. But beneath the surface lies a powerful simulation engine. The game's mechanics are abstract. The engine does not know about the game world. However, the mechanics rely on words, not math, and the players know what these words correspond to in the world, every action has a specific reference in the game world. And because the mechanics are designed for simulation, the game feels specifically simulated, even though it doesn't have to be mechanically complicated.

*** A Toolkit, Not a Straitjacket
The core rules are a starting point. Dreamforge is designed to be modular and adaptable. The game does not have rules for laser blasters or magic spells. Instead, the game provides the tools to create those things and more. Players can add, remove, and modify rules. This allows players to perfectly match the story they want to create together.

**What will you forge?**

This document is your guide to the core mechanics of Dreamforge. Read on, and start building your dream.
